version: "3"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.1"
    container_name: go_elk_example_elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - go-elk-example

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.15.1"
    container_name: go_elk_example_kibana
    ports:
      - "5601:5601"
    networks:
      - go-elk-example

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.15.1"
    container_name: go_elk_example_filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../logs:/var/logs
    networks:
      - go-elk-example

  metricbeat:
    build: ./metricbeat
    container_name: go_elk_example_metricbeat
    environment:
      ELASTICSEARCH_HOSTS: elasticsearch:9200
      KIBANA_HOST: kibana:5601
    volumes:
      - metricbeat_data:/usr/share/metricbeat/data
    networks:
      - go-elk-example
    depends_on:
      - elasticsearch
      - kibana

networks:
  go-elk-example:

volumes:
  elasticsearch_data:
  metricbeat_data:
