metricbeat.config.modules:

output.elasticsearch:
  hosts:
   - "elasticsearch:9200"
  indices:
    - index: "goelkmetr-%{[agent.version]}-%{+yyyy.MM.dd}"

metricbeat.modules:
  - module: golang
    metricsets:
      - expvar
      - heap
    period: 10s
    hosts:
      - "192.168.0.182:8080"
    heap.path: "/debug/vars"
    expvar:
      namespace: "example"
      path: "/debug/vars"
